from django.db import models


class VpaTable(models.Model):
    id = models.AutoField(primary_key=True)
    gene_id_ENSG = models.CharField(max_length=32, verbose_name="Ensemble ID", help_text='Ensemble Gene Uniq ID')
    # csv表中原有的字段
    individual = models.FloatField(verbose_name="Individual")
    age = models.FloatField(verbose_name="Age")
    condition = models.FloatField(verbose_name="Condition")
    rin = models.FloatField(verbose_name="RIN")
    hemoglobin = models.FloatField(verbose_name="Hemoglobin")
    sex = models.FloatField(verbose_name="Sex")
    state = models.FloatField(verbose_name="State")
    residuals = models.FloatField(verbose_name="Residuals")

    class Meta:
        app_label = 'ltbm'


class TsaTable(models.Model):
    id = models.AutoField(primary_key=True)
    gene_id_ENSG = models.CharField(max_length=32, verbose_name="Ensemble ID", help_text='Ensemble Gene Uniq ID')
    # csv表中原有的字段
    cluster = models.CharField(max_length=16, verbose_name="Cluster")
    is_core = models.BooleanField(verbose_name="Is Core")

    class Meta:
        app_label = 'ltbm'


class GeneVstExpTable(models.Model):
    id = models.AutoField(primary_key=True)
    gene_id_ENSG = models.CharField(max_length=32, verbose_name="Ensemble ID", help_text='Ensemble Gene Uniq ID')
    # csv表中原有的字段
    bcr01_a = models.FloatField(db_column='BCR01.A')
    bcr02_a = models.FloatField(db_column='BCR02.A')
    bcr03_a = models.FloatField(db_column='BCR03.A')
    bcr06_a = models.FloatField(db_column='BCR06.A')
    bcr07_a = models.FloatField(db_column='BCR07.A')
    bcr08_a = models.FloatField(db_column='BCR08.A')
    bcr09_a = models.FloatField(db_column='BCR09.A')
    bcr10_a = models.FloatField(db_column='BCR10.A')
    bcr11_a = models.FloatField(db_column='BCR11.A')
    bcr12_a = models.FloatField(db_column='BCR12.A')
    bcr13_a = models.FloatField(db_column='BCR13.A')
    bcr14_a = models.FloatField(db_column='BCR14.A')
    bcr15_a = models.FloatField(db_column='BCR15.A')
    bcr16_a = models.FloatField(db_column='BCR16.A')
    bcr17_a = models.FloatField(db_column='BCR17.A')
    bcr18_a = models.FloatField(db_column='BCR18.A')
    bcr19_a = models.FloatField(db_column='BCR19.A')
    bcr20_a = models.FloatField(db_column='BCR20.A')
    bcr21_a = models.FloatField(db_column='BCR21.A')
    bcr01_b = models.FloatField(db_column='BCR01.B')
    bcr02_b = models.FloatField(db_column='BCR02.B')
    bcr03_b = models.FloatField(db_column='BCR03.B')
    bcr04_b = models.FloatField(db_column='BCR04.B')
    bcr05_b = models.FloatField(db_column='BCR05.B')
    bcr06_b = models.FloatField(db_column='BCR06.B')
    bcr07_b = models.FloatField(db_column='BCR07.B')
    bcr08_b = models.FloatField(db_column='BCR08.B')
    bcr09_b = models.FloatField(db_column='BCR09.B')
    bcr10_b = models.FloatField(db_column='BCR10.B')
    bcr11_b = models.FloatField(db_column='BCR11.B')
    bcr12_b = models.FloatField(db_column='BCR12.B')
    bcr13_b = models.FloatField(db_column='BCR13.B')
    bcr14_b = models.FloatField(db_column='BCR14.B')
    bcr15_b = models.FloatField(db_column='BCR15.B')
    bcr16_b = models.FloatField(db_column='BCR16.B')
    bcr17_b = models.FloatField(db_column='BCR17.B')
    bcr18_b = models.FloatField(db_column='BCR18.B')
    bcr19_b = models.FloatField(db_column='BCR19.B')
    bcr20_b = models.FloatField(db_column='BCR20.B')
    bcr21_b = models.FloatField(db_column='BCR21.B')
    bcr01_c = models.FloatField(db_column='BCR01.C')
    bcr02_c = models.FloatField(db_column='BCR02.C')
    bcr03_c = models.FloatField(db_column='BCR03.C')
    bcr04_c = models.FloatField(db_column='BCR04.C')
    bcr05_c = models.FloatField(db_column='BCR05.C')
    bcr06_c = models.FloatField(db_column='BCR06.C')
    bcr07_c = models.FloatField(db_column='BCR07.C')
    bcr08_c = models.FloatField(db_column='BCR08.C')
    bcr09_c = models.FloatField(db_column='BCR09.C')
    bcr10_c = models.FloatField(db_column='BCR10.C')
    bcr11_c = models.FloatField(db_column='BCR11.C')
    bcr12_c = models.FloatField(db_column='BCR12.C')
    bcr13_c = models.FloatField(db_column='BCR13.C')
    bcr14_c = models.FloatField(db_column='BCR14.C')
    bcr15_c = models.FloatField(db_column='BCR15.C')
    bcr16_c = models.FloatField(db_column='BCR16.C')
    bcr17_c = models.FloatField(db_column='BCR17.C')
    bcr18_c = models.FloatField(db_column='BCR18.C')
    bcr19_c = models.FloatField(db_column='BCR19.C')
    bcr20_c = models.FloatField(db_column='BCR20.C')
    bcr21_c = models.FloatField(db_column='BCR21.C')
    bcr01_d = models.FloatField(db_column='BCR01.D')
    bcr02_d = models.FloatField(db_column='BCR02.D')
    bcr03_d = models.FloatField(db_column='BCR03.D')
    bcr04_d = models.FloatField(db_column='BCR04.D')
    bcr05_d = models.FloatField(db_column='BCR05.D')
    bcr06_d = models.FloatField(db_column='BCR06.D')
    bcr07_d = models.FloatField(db_column='BCR07.D')
    bcr08_d = models.FloatField(db_column='BCR08.D')
    bcr09_d = models.FloatField(db_column='BCR09.D')
    bcr10_d = models.FloatField(db_column='BCR10.D')
    bcr11_d = models.FloatField(db_column='BCR11.D')
    bcr12_d = models.FloatField(db_column='BCR12.D')
    bcr13_d = models.FloatField(db_column='BCR13.D')
    bcr14_d = models.FloatField(db_column='BCR14.D')
    bcr15_d = models.FloatField(db_column='BCR15.D')
    bcr16_d = models.FloatField(db_column='BCR16.D')
    bcr17_d = models.FloatField(db_column='BCR17.D')
    bcr18_d = models.FloatField(db_column='BCR18.D')
    bcr19_d = models.FloatField(db_column='BCR19.D')
    bcr20_d = models.FloatField(db_column='BCR20.D')
    bcr21_d = models.FloatField(db_column='BCR21.D')
    bcr01_e = models.FloatField(db_column='BCR01.E')
    bcr02_e = models.FloatField(db_column='BCR02.E')
    bcr03_e = models.FloatField(db_column='BCR03.E')
    bcr04_e = models.FloatField(db_column='BCR04.E')
    bcr05_e = models.FloatField(db_column='BCR05.E')
    bcr06_e = models.FloatField(db_column='BCR06.E')
    bcr07_e = models.FloatField(db_column='BCR07.E')
    bcr08_e = models.FloatField(db_column='BCR08.E')
    bcr09_e = models.FloatField(db_column='BCR09.E')
    bcr10_e = models.FloatField(db_column='BCR10.E')
    bcr11_e = models.FloatField(db_column='BCR11.E')
    bcr12_e = models.FloatField(db_column='BCR12.E')
    bcr13_e = models.FloatField(db_column='BCR13.E')
    bcr14_e = models.FloatField(db_column='BCR14.E')
    bcr15_e = models.FloatField(db_column='BCR15.E')
    bcr16_e = models.FloatField(db_column='BCR16.E')
    bcr17_e = models.FloatField(db_column='BCR17.E')
    bcr18_e = models.FloatField(db_column='BCR18.E')
    bcr19_e = models.FloatField(db_column='BCR19.E')
    bcr20_e = models.FloatField(db_column='BCR20.E')
    bcr21_e = models.FloatField(db_column='BCR21.E')
    bcr01_f = models.FloatField(db_column='BCR01.F')
    bcr02_f = models.FloatField(db_column='BCR02.F')
    bcr03_f = models.FloatField(db_column='BCR03.F')
    bcr04_f = models.FloatField(db_column='BCR04.F')
    bcr05_f = models.FloatField(db_column='BCR05.F')
    bcr06_f = models.FloatField(db_column='BCR06.F')
    bcr07_f = models.FloatField(db_column='BCR07.F')
    bcr08_f = models.FloatField(db_column='BCR08.F')
    bcr09_f = models.FloatField(db_column='BCR09.F')
    bcr10_f = models.FloatField(db_column='BCR10.F')
    bcr11_f = models.FloatField(db_column='BCR11.F')
    bcr12_f = models.FloatField(db_column='BCR12.F')
    bcr13_f = models.FloatField(db_column='BCR13.F')
    bcr14_f = models.FloatField(db_column='BCR14.F')
    bcr15_f = models.FloatField(db_column='BCR15.F')
    bcr16_f = models.FloatField(db_column='BCR16.F')
    bcr17_f = models.FloatField(db_column='BCR17.F')
    bcr18_f = models.FloatField(db_column='BCR18.F')
    bcr19_f = models.FloatField(db_column='BCR19.F')
    bcr20_f = models.FloatField(db_column='BCR20.F')
    bcr21_f = models.FloatField(db_column='BCR21.F')
    bcr01_g = models.FloatField(db_column='BCR01.G')
    bcr02_g = models.FloatField(db_column='BCR02.G')
    bcr04_g = models.FloatField(db_column='BCR04.G')
    bcr05_g = models.FloatField(db_column='BCR05.G')
    bcr06_g = models.FloatField(db_column='BCR06.G')
    bcr07_g = models.FloatField(db_column='BCR07.G')
    bcr08_g = models.FloatField(db_column='BCR08.G')
    bcr09_g = models.FloatField(db_column='BCR09.G')
    bcr10_g = models.FloatField(db_column='BCR10.G')
    bcr11_g = models.FloatField(db_column='BCR11.G')
    bcr12_g = models.FloatField(db_column='BCR12.G')
    bcr13_g = models.FloatField(db_column='BCR13.G')
    bcr14_g = models.FloatField(db_column='BCR14.G')
    bcr15_g = models.FloatField(db_column='BCR15.G')
    bcr16_g = models.FloatField(db_column='BCR16.G')
    bcr17_g = models.FloatField(db_column='BCR17.G')
    bcr18_g = models.FloatField(db_column='BCR18.G')
    bcr19_g = models.FloatField(db_column='BCR19.G')
    bcr21_g = models.FloatField(db_column='BCR21.G')
    model_type = models.CharField(max_length=8, verbose_name="Model")
    mcr01 = models.FloatField(db_column='MCR01', blank=True, null=True)
    mcr02 = models.FloatField(db_column='MCR02', blank=True, null=True)
    mcr03 = models.FloatField(db_column='MCR03', blank=True, null=True)
    mcr05 = models.FloatField(db_column='MCR05', blank=True, null=True)
    mcr06 = models.FloatField(db_column='MCR06', blank=True, null=True)
    mcr07 = models.FloatField(db_column='MCR07', blank=True, null=True)
    mcr08 = models.FloatField(db_column='MCR08', blank=True, null=True)
    mcr09 = models.FloatField(db_column='MCR09', blank=True, null=True)
    mcr10 = models.FloatField(db_column='MCR10', blank=True, null=True)
    mcr11 = models.FloatField(db_column='MCR11', blank=True, null=True)
    mcr12 = models.FloatField(db_column='MCR12', blank=True, null=True)
    mcr14 = models.FloatField(db_column='MCR14', blank=True, null=True)
    mcr15 = models.FloatField(db_column='MCR15', blank=True, null=True)
    mcr16 = models.FloatField(db_column='MCR16', blank=True, null=True)
    mcr17 = models.FloatField(db_column='MCR17', blank=True, null=True)
    mcr18 = models.FloatField(db_column='MCR18', blank=True, null=True)
    mcr19 = models.FloatField(db_column='MCR19', blank=True, null=True)
    mcr20 = models.FloatField(db_column='MCR20', blank=True, null=True)
    mcr21 = models.FloatField(db_column='MCR21', blank=True, null=True)
    ocr01 = models.FloatField(db_column='OCR01', blank=True, null=True)
    ocr02 = models.FloatField(db_column='OCR02', blank=True, null=True)
    ocr03 = models.FloatField(db_column='OCR03', blank=True, null=True)
    ocr04 = models.FloatField(db_column='OCR04', blank=True, null=True)
    ocr05 = models.FloatField(db_column='OCR05', blank=True, null=True)
    ocr06 = models.FloatField(db_column='OCR06', blank=True, null=True)
    ocr07 = models.FloatField(db_column='OCR07', blank=True, null=True)
    ocr08 = models.FloatField(db_column='OCR08', blank=True, null=True)
    ocr09 = models.FloatField(db_column='OCR09', blank=True, null=True)
    ocr10 = models.FloatField(db_column='OCR10', blank=True, null=True)
    ocr11 = models.FloatField(db_column='OCR11', blank=True, null=True)
    ocr12 = models.FloatField(db_column='OCR12', blank=True, null=True)
    ocr13 = models.FloatField(db_column='OCR13', blank=True, null=True)
    ocr14 = models.FloatField(db_column='OCR14', blank=True, null=True)
    ocr15 = models.FloatField(db_column='OCR15', blank=True, null=True)
    ocr16 = models.FloatField(db_column='OCR16', blank=True, null=True)
    ocr17 = models.FloatField(db_column='OCR17', blank=True, null=True)
    ocr18 = models.FloatField(db_column='OCR18', blank=True, null=True)
    ocr19 = models.FloatField(db_column='OCR19', blank=True, null=True)
    ocr20 = models.FloatField(db_column='OCR20', blank=True, null=True)
    ocr21 = models.FloatField(db_column='OCR21', blank=True, null=True)
    ocr22 = models.FloatField(db_column='OCR22', blank=True, null=True)
